#pragma config(Motor,  port2,           motor1,        tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port3,           motor2,        tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port4,           motor3,        tmotorVex393_MC29, openLoop, driveRight)
#pragma config(Motor,  port5,           motor4,        tmotorVex393_MC29, openLoop, driveRight)
#pragma config(Motor,  port6,           balla_motor,   tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port7,           launcy_boi,    tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)
// Competition Control
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)
#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

int ball_loader;
int ball_launch;

void pre_auton()
{
	bStopTasksBetweenModes = true;
}

task autonomous()
{
	motor[port2] = 127;
	motor[port3] = 127;
	motor[port4] = 127;
	motor[port5] = 127;
	wait(1, seconds);
	motor[port2] = -127;
	motor[port3] = -127;
	motor[port4] = -127;
	motor[port5] = -127;
	wait(860, milliseconds);
	startTask(usercontrol);
}

task usercontrol()
{
	while ( 1 == 1 )
	{
		//Drive
		tankControl(Ch2, Ch3, 10);

		// Autonomous Start and Tele-op Stop
		if(vexRT[Btn7U] == 1)
		{
			startTask(autonomous);
			stopTask(usercontrol);
		}
		// Ball Spinny Thing (BPU)
		// 6U is Intake, 5U is spit, and 5D & 6D are stop
		// Normal rotation
		if(vexRT[Btn6U] == 1)
		{
			ball_loader = 127;
		}
		else if(vexRT[Btn6D] == 1)
		{
			ball_loader = 0;
			ball_launch = 0;
		}

		// Reversed Rotation
		else if(vexRT[Btn5U] == 1)
		{
			ball_loader = -127;
		}
		else if(vexRT[Btn5D] == 1)
		{
			ball_loader = 0;
			ball_launch = 0;
		}

		motor[port6] = ball_loader;

		// Ball Launch Start
		// 8D is pull
		if(vexRT[Btn8D] == 1)
		{
			ball_launch = 127;
		}
		motor[port7] = ball_launch;
	}
}
