#pragma config(Motor,  port2,           motor1,        tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port3,           motor2,        tmotorVex393_MC29, openLoop, driveRight)
#pragma config(Motor,  port4,           claw_lift,     tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port5,           claw_lift2,    tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port6,           claw_lift3,    tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port7,           claw_cap,      tmotorVex269_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)
// Competition Control
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)
#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

void pre_auton()
{
	bStopTasksBetweenModes = true;
}

task autonomous()
{
	motor[port4] = -32;
	motor[port5] = -32;
	motor[port6] = -32;
	wait(300, milliseconds);
	motor[port2] = 127;
	motor[port3] = 127;
	wait(800, milliseconds);
	motor[port2] = 127;
	motor[port3] = -127;
	wait(800, milliseconds);
	motor[port2] = 127;
	motor[port3] = 127;
	wait(1250, milliseconds);

	startTask(usercontrol);
}

task usercontrol()
{
	motor[port7] = 0;
	while ( 1 == 1 )
	{
		if(vexRT[Btn7L] == 1)
		{
			startTask(autonomous);
			stopTask(usercontrol);
		}
		//Drive
		tankControl(Ch2, Ch3, 10);
		//Lift servo
		if(vexRT[Btn8U] == 1)
		{
			motor[port4] = 96;
			motor[port5] = 96;
			motor[port6] = 96;
		}
		else if(vexRT[Btn8D] == 1)
		{
			motor[port4] = -96;
			motor[port5] = -96;
			motor[port6] = -96;
		}
		else //if(vexRT[Btn8R] == 1)
		{
			motor[port4] = 0;
			motor[port5] = 0;
			motor[port6] = 0;
		}
		if(vexRT[Btn7U] == 1)
		{
			motor[port7] = 100;
		}
		if(vexRT[Btn7D] == 1)
		{
			motor[port7] = 0;
		}
	}
}
