#pragma config(Motor,  port2,           motor1,        tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port3,           motor2,        tmotorVex269_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
task main()
{
	while (1 == 1)
	{
		motor[port2] = 127;
		motor[port3] = 127;
	}
}
