#pragma config(Motor,  port8,           bla1,          tmotorServoStandard, openLoop)
#pragma config(Motor,  port9,           bla2,          tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	motor[port8] = 0;
	motor[port9] = 0;

}
