#pragma config(Sensor, dgtl12, ArmStop,        sensorTouch)
#pragma config(Motor,  port2,           motor1,        tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port3,           motor2,        tmotorVex393_MC29, openLoop, driveRight)
#pragma config(Motor,  port4,           lift_motor1,   tmotorVex269_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int bumpstop;

task main()
{
	bumpstop = 0;
	while  ( 1 == 1 )
	{
		// Drive control
		tankControl(Ch2, Ch3, 10);

		// Claw-arm thing
		if( SensorValue (ArmStop) == 1 )
		{
			bumpstop = 0;
		}
		else if( SensorValue (ArmStop) == 0 )
		{
			bumpstop = (vexRT[Btn8D] * -127);
		}

		// Go up
		if(vexRT[Btn8U] == 1)
		{
			motor[port4] = 127;
		}
		// Stop
		else if(vexRT[Btn8R] == 1)
		{
			motor[port4] = 0;
		}

		// Stop
		else if(vexRT[Btn8L] == 1)
		{
			motor[port4] = 0;
		}

		// Drop it like it's hot
		else if(vexRT[Btn8D] == 1)
		{
			motor[port4] = bumpstop;
		}
	}
}
